num_gpus: 4
model_path: FastVideo/FastHunyuan-diffusers
master_port: 29503
sp_size: 4 
tp_size: 4 
height: 720 
width: 1280 
num_frames: 125 
num_inference_steps: 6 
guidance_scale: 1 
embedded_cfg_scale: 6 
flow_shift: 17 
prompt_path: ./assets/prompt.txt 
seed: 1024 
output_path: outputs_video/ 
vae-sp: True